---
title: "Artículo RBM"
format:
   html:
     toc: true
     html-math-method: katex
     embed-resources: true
     self-contained-math: true
     df-print: kable
bibliography: bibliografia.bib
---

## Abstract

Síntesis breve y clara del contenido completo del artículo. Debe incluir el objetivo principal del estudio, la metodología empleada, los resultados más relevantes y las conclusiones principales.

## Introducción

La movilidad urbana constituye un componente esencial en la calidad de vida de los habitantes de las grandes ciudades, al incidir directamente en el acceso a oportunidades educativas, laborales y recreativas. En particular, la Zona Metropolitana del Valle de México (ZMVM) enfrenta desde hace décadas retos asociados con la saturación vial, la desigualdad en el acceso a medios de transporte, y la alta dependencia del automóvil privado. [@alfonso2020]

“En una región caracterizada por la desigualdad, las deficiencias de los sistemas de transporte público impactan de forma desproporcionada a los más vulnerables. Solamente el 43% de la población de América Latina y el Caribe tiene acceso conveniente al transporte público, y sus usuarios gastan 70% más tiempo en el desplazamiento al trabajo comparados a quienes utilizan vehículos privados”. (Plataforma Urbana y de Ciudades de América Latina y Caribe, 2023) [@plataforma2023]

En 2017, el Instituto Nacional de Estadística y Geografía (INEGI), en colaboración con el Instituto de Ingeniería de la UNAM y la Secretaría de Movilidad de la Ciudad de México, llevó a cabo la “Encuesta Origen-Destino en Hogares de la ZMVM”. [@inegi_eod2017] Este levantamiento tuvo como propósito caracterizar los desplazamientos diarios de los habitantes de la metrópoli, registrando variables como motivo del viaje, duración, medio de transporte, horarios de salida y llegada, así como información sociodemográfica de los hogares y personas encuestadas.

El presente artículo se centra en responder cuatro consultas específicas de esta base de datos generada por el INEGI:

1.  ¿Cuál es la probabilidad de que una mujer utilice el transporte público en comparación con un hombre?

2.  ¿Qué tan probable es que una persona tenga más de un automóvil o utilice transporte privado, dado que se trata de un hombre entre 20 y 45 años con estrato sociodemográfico bajo?

3.  ¿Las personas con un estrato sociodemográfico bajo realizan más viajes en días hábiles que en días inhábiles?

4.  ¿Cuál es la probabilidad de que una persona utilice transporte público durante las horas pico en comparación con las horas de menor tráfico?

Dado que la movilidad está influenciada por diversos factores interrelacionados resulta difícil explicar estas relaciones con un enfoque únicamente determinista. El uso de modelos probabilísticos ofrece una manera más robusta de capturar estas interacciones y de responder a las preguntas planteadas.

La idea central de este razonamiento probabilístico se basa en el teorema de Bayes y en las probabilidades condicionales para modelar las relaciones entre distintos eventos. En lugar de afirmar con certeza que “mañana lloverá”, este enfoque permite expresar escenarios más realistas, como decir que “existe un 70% de probabilidad de que mañana llueva”. [@bhattarai2025]

El Teorema de Bayes, permite actualizar la probabilidad de una hipótesis H al observar nueva evidencia E:

\begin{equation}
P(H | E) = \frac{P(E | H)P(H)}{P(E)}
\end{equation}

Donde $P(H)$ es la probabilidad previa de la hipótesis, $P(E|H)$ es la probabilidad de observar la evidencia dado que $H$ es cierta, y $P(H|E)$ es la probabilidad posterior, actualizada después de incorporar la evidencia.

Una red bayesiana es un modelo gráfico probabilístico que utiliza un grafo acíclico dirigido (DAG, por sus siglas en inglés, Directed Acyclic Graph) para describir un conjunto de variables y sus relaciones condicionales . Las redes bayesianas funcionan para pronosticar un evento que ya ha ocurrido y predecir la probabilidad de que el factor contribuyente esté entre varias causas conocidas.

## Metodología    

Formalmente, una red bayesiana se define como el par $(G,P)$, donde $G=(V,E)$ es un DAG cuyos nodos $V=\{X_1,X_2,…,X_n\}$, corresponden a las variables de interés y los arcos $E$ representan dependencias directas, mientras que $P$ es el conjunto de distribuciones de probabilidad condicional asociadas a cada nodo. La probabilidad conjunta de todas las variables se factoriza como:

\begin{equation}
P(X_1, X_2, \dots, X_n) = \prod_{i=1}^{n} P(X_i | \text{Parents}(X_i))
\end{equation}

Esta estructura permite analizar relaciones de dependencia complejas, realizar inferencias sobre escenarios hipotéticos y evaluar cómo distintos factores individuales y contextuales influyen en los patrones de transporte en la ZMVM.

Las redes bayesianas multinomiales ofrecen una herramienta poderosa para modelar interacciones probabilísticas entre variables, permitiendo no sólo estimar la probabilidad de determinados comportamientos de viaje, sino también evaluar cómo cambian dichas probabilidades bajo distintos escenarios.

Para dar respuesta a las preguntas, se trabajará con información proveniente de distintos módulos de la encuesta, de los cuales se extraerán variables clave, estas son: sexo, edad, estrato sociodemográfico, número de automóviles disponibles, clasificación del día y hora del viaje, así como el medio de transporte empleado. El análisis busca identificar dependencias significativas entre estas variables y aportar evidencia sobre cómo factores individuales y contextuales inciden en la movilidad dentro de la ZMVM.

Para crear los modelos que se presentarán posteriormente, se identificaron las siguientes variables de interés a partir de las preguntas dadas.

* `sexo`: Mujer, Hombre
* `tipoTransporte`: Ninguno, Publico, Privado, Publico y privado
* `masDeUnCarro`: No, Si
* `edad`: Joven, Adulto joven, Adulto, Adulto mayor
* `estrato`: Bajo, Medio bajo, Medio alto, Alto
* `diaViaje`: Entre semana, Sabado
* `horaPico`: No, Si

Es de notar, que las primeras dos preguntas tratan sobre las personas que realizaron los viajes, mientras que las últimas dos hablan sobre los viajes como tal, y dado que una persona puede tener varios viajes registrados, se crearán dos bases de datos desde la base original. En la primera, cada registro corresponde a una persona, mientras que en la segunda, cada registro corresponde a un viaje.

Lo anterior implica que las variables dentro de cada base de datos pueden diferir, pues por ejemplo, si un viaje se realizó en hora pico solamente tiene sentido en una base de datos sobre viajes, no sobre personas (como se mencionó, una persona puede tener varios viajes, con solamente algunos realizados durante hora pico). Las variables que se utilizarán para las primeras dos preguntas son: `sexo`, `edad`, `estrato`, `tipoTransporte` y `masDeUnCarro`; el proceso para obtenerlas se puede consultar en el [Apéndice A](#apéndice-a). Por otro lado, las variables para responder las últimas dos preguntas son: tipoTransporte, estrato, diaViaje y horasPico, el proceso de su obtención se encuentra en el [Apéndice B](#apéndice-b).

Habiendo identificado las variables de interés y procesado de datos, se realizarán dos propuestas de DAGs para cada base de datos, con sus respectivas variables. Estos grafos representan las relaciones de dependencia que se considera intuitivamente podrían existir entre las variables.

Con cada una de las DAGs propuestas, se generará una red bayesiana, con la cual se realizarán pruebas de independencia condicional para cada arco. Esto permitirá determinar la significancia de las relaciones propuestas entre las variables, así como ver cuál de las redes representa un mejor ajuste para los datos.

La prueba de independencia condicional que se utilizará para probar la significancia de un arco entre dos variables de los grafos estará basada en el criterio de información mutua, la cual mide qué tanta información es compartida entre dos nodos, de la librería de bnlearn de R. [@JSSv105i08]

Posteriormente, se generará una DAG óptima para cada base de datos con el algoritmo de hill climbing. Este algoritmo busca optimizar un criterio dado, mientras elimina y agrega un arco a la vez, escogiendo el movimiento que represente la mayor mejora del criterio. El criterio a maximizar será el de información bayesiano (BIC), al ser este un criterio empleado para la selección del mejor modelo entre una cantidad finita de modelos, considerando la verosimilitud y la complejidad de los modelos. [@scutari2021bayesian]

A pesar de que el algoritmo de hill climbing genera un DAG óptimo respecto a la métrica del BIC, es necesario considerar la pertinencia de las relaciones que genera, ya que este no conoce el contexto de las variables o lo que representan y podría poner una relación que no tiene sentido.

Una vez habiendo seleccionado los DAGs óptimos para cada conjunto de datos, se responderán las preguntas primero estableciendo las probabilidades esperadas, con las cuales se realizará inferencia exacta o aproximada, dependiendo del caso. Si se puede obtener una probabilidad directamente de la red bayesiana generada, se realizará esto. En caso contrario, se estimará la probabilidad utilizando el método de Monte Carlo, realizando múltiples simulaciones del modelo que se resumirán en el estimador de interés. Para ello, se utilizará el algoritmo logic sampling, el cual simula observaciones de la red bayesiana que son independientes entre sí, y estima la probabilidad con la cantidad de observaciones que cumplen el evento sobre la cantidad de observaciones que cumplen con la evidencia. [@scutari2021bayesian]


## Apéndice A

El primer set de datos que se generó contiene las variables de interés relacionadas a las primeras dos preguntas, las cuales incluyen `sexo`, `tipoTransporte`, `masDeUnCarro`, `edad` y `estrato.` Para ello, se obtuvieron las columnas de $sexo$ y $edad$ desde el archivo *tviaje_eod2017/conjunto_de_datos/tviaje.csv*.

#### Variable`sexo`

La columna de $sexo$ en el archivo de viajes contiene valores de $1$ y $2$, cuyos significados se encuentran en el catálogo vinculado a este archivo, por lo que se reemplazaron los valores de acuerdo con el catálogo en *tviaje_eod2017/catalogos/sexo.csv*.

#### Variable `edad`

La variable `edad` fue clasificada en 4 categorías:

* *Joven:* Persona menor a $20$ años.
* *Adulto joven:* Persona entre $20$ y $45$ años.
* *Adulto:* Persona entre $46$ y $64$ años.
* *Adulto mayor:* Persona mayor a los $64$ años.

#### Variable `tipoTransporte`

Utilizando el identificador del viaje ($id\_via$) dentro de este mismo conjunto de datos, se realizó una unión con los datos de transporte (archivo con la ruta *ttransporte_eod2017/conjunto_de_datos/ttransporte.csv*), para obtener las variables $p5\_3$ y $p5\_14$, que representan el día de viaje y el medio de transporte respectivamente. Con ello, se contó la cantidad de veces en las que se viajó en transporte público (transportes correspondientes a los números $2, 5, 6, 8, 10, 11, 12, 13, 15$ en la variable $p5\_14$) y la cantidad de veces en las que se viajó en transporte privado (transportes correspondientes a los números $1, 3, 4, 7, 9, 14, 16, 17, 18, 19$ en la variable $p5\_14$) por persona.

A la variable `tipoTransporte` se le asignó el valor “Ninguno” cuando se viajó $0$ veces en transporte público y $0$ veces en transporte privado, “Publico” cuando se viajó solamente en transporte público, “Privado” cuando se viajó solamente en transporte privado, y “Publico y privado” cuando se viajó por lo menos una vez en ambos tipos de transporte.

Posteriormente, se realizó una unión entre la tabla con la información de los hogares (*thogar_eod2017/conjunto_de_datos/thogar.csv*) y la de información sociodemográfica (*tsdem_eod2017/conjunto_de_datos/tsdem.csv*), para vincular a través del identificador del hogar ($id\_hog$) la información del identificador de la persona ($id\_soc$) junto con la cantidad de autos o camionetas que se tienen para transportarse diariamente ($p2\_1\_1$) y el estrato sociodemográfico ($estrato$).

#### Variable `masDeUnCarro`

Utilizando la columna de $p2\_1\_1$, la cantidad de autos o camionetas para transporte, se asignó el valor de “No” si se tenían $0$ o $1$ autos, y se asignó “Si” cuando se tenían dos o más autos.

#### Variable `estrato`

Para la variable `estrato`, se renombraron las categorías de acuerdo con el catálogo *thogar_eod2017/catalogos/estrato.csv*.

## Apéndice B

El segundo set de datos se utilizará para responder las preguntas $3$ y $4$, las cuales tienen como variables de interés a `estrato`, `diaViaje`, `tipoTransporte` y `horaPico`. Para ello, de la información de viajes que se encuentra en *tviaje_eod2017/conjunto_de_datos/tviaje.csv*, se extrae el estrato sociodemográfico ($estrato$), la clasificación del día de viaje ($p5\_3$), y el horario en el que se realizó el viaje ($p5\_9\_1$ para la hora de inicio, $p5\_9\_2$ para el minuto de inicio, $p5\_10\_1$ para la hora de fin, $p5\_10\_2$ para el minuto de fin).

#### Variable `diaViaje`

La columna de la clasificación del día de viaje, $p5\_3$, presenta valores de $1$ y $2$, los cuales hacen referencia a que se viaje entre semana o a que se viaje en sábado respectivamente, de acuerdo con el catálogo que se encuentra en *tviaje_eod2017/catalogos/p5_3.csv*. Conociendo esto, se reemplazó el valor de $1$ a “Entre semana” y el de $2$ a “Sabado” para una mayor claridad en las categorías.

#### Varibale `estrato`

En la variable `estrato`, se renombraron las categorías de acuerdo con el catálogo *thogar_eod2017/catalogos/estrato.csv*.

#### Variable `tipoTransporte`

Utilizando el identificador del viaje ($id\_via$) en el conjunto de datos del transporte (el cual se encuentra en *ttransporte_eod2017/conjunto_de_datos/ttransporte.csv*), se contó en cuántas ocasiones se viajó en transporte público y en transporte privado en un solo viaje. Al igual que en el **Apéndice A**, se tomaron a los valores de $2, 5, 6, 8, 10, 11, 12, 13, 15$ en la variable $p5\_14$ como transportes públicos y a los valores $1, 3, 4, 7, 9, 14, 16, 17, 18, 19$ como transporte privado. A partir de este conteo, se le asignó la categoría de “Ninguno” a la variable `tipoTransporte` cuando no se viajó ni en transporte público ni privado, “Publico” cuando el viaje solamente se realizó en transporte público, “Privado” si el viaje solamente se realizó en transporte privado, y “Publico y privado” en caso de que el viaje se haya realizado tanto en transporte público como en transporte privado.

#### Variable `horaPico`

Para determinar si un viaje se llevó a cabo en hora pico o no, se asume que los horarios pico se encuentran entre las $7:30$ y $9:30$ horas, así como entre las $17:30$ y $20:00$ horas (poner referencia?). Con ello, se calculó cuántos minutos del viaje se dieron durante algún horario pico, y se dividió entre el total de minutos que duró el viaje para obtener una proporción del tiempo del viaje que se llevó a cabo en hora pico respecto a la duración total del viaje. En el caso en que el viaje se haya realizado en horario pico más de la mitad de su duración, este se considera que fue en hora pico. En caso contrario, se considera el viaje como no realizado en hora pico.

Un caso a considerar a la hora de calcular las horas picos es que existen viajes que se terminaron en una hora previa a la hora de inicio, no en una hora posterior. Esto se asume que indica que el viaje se da en dos días, por lo que a la hora de obtener cuánto tiempo del viaje se llevó a cabo en horario pico, se considera primero el tiempo desde el momento del inicio del viaje hasta el fin del día, a lo cual se le agrega el tiempo entre el inicio del día y el momento del fin del viaje.

La manera en la que se calculó la duración del viaje en horario pico es la siguiente:

* Se tomó el valor máximo entre el inicio del viaje y el inicio del primer horario pico, al cual referiremos como $a$.
* Se tomó el valor mínimo entre el fin del viaje y el fin del primer horario pico, al cual referiremos como $b$.
* En caso de $a<b$, se considera que el tiempo $b-a$ se realizó en horario pico. Sino, no hubo traslape con dicho horario pico.
* Se repiten los pasos anteriores para el segundo horario pico, y se suman estos tiempos.

Para el caso particular en donde el viaje se realiza durante dos días, se secciona el horario, así que el traslape que se da en la hora de inicio hasta el final del día con los horarios pico, se le añade el traslape que se da entre el inicio del día hasta el final del viaje con los horarios pico.

## Referencias

::: bibliography
:::
