---
title: "DAGs"
format: html
editor: visual
---

## DAGS

Importar librería y cargar los datos.

```{r}
library(bnlearn)
#Para la primera query
data12 = read.csv("q12.csv", stringsAsFactors = TRUE)
#Segunda query
data34 = read.csv("q34.csv", stringsAsFactors = TRUE)
```

### Primera query

Dag propuesta 1

```{r}
dag1 = empty.graph(nodes = c("sexo", "edad", "tipoTransporte", "masDeUnCarro", "estrato"))


arc_set = matrix(c("sexo", "estrato",
                   "edad", "estrato",
                   "estrato", "masDeUnCarro",
                   "estrato", "tipoTransporte",
                   "masDeUnCarro", "tipoTransporte"),
                 byrow = TRUE, ncol = 2,
                 dimnames = list(NULL, c("from", "to")))

arcs(dag1) = arc_set
dag1
```

```{r}
arc.strength(dag1, data = data12, criterion = "mi")
```

Todos nuestros valores Todas las relaciones de dependencia son significativas

```{r}
score(dag1, data = data12, type = "bic")
```

Dag propuesta 2, para query 1

```{r}
dag2 = empty.graph(nodes = c("sexo", "edad", "tipoTransporte", "masDeUnCarro", "estrato"))

arc_set2 = matrix(c("sexo", "estrato",
                   "estrato", "masDeUnCarro",
                   "edad", "masDeUnCarro",
                   "masDeUnCarro", "tipoTransporte"),
                 byrow = TRUE, ncol = 2,
                 dimnames = list(NULL, c("from", "to")))
arcs(dag2) = arc_set2
dag2
```

```{r}
arc.strength(dag2, data = data12, criterion = "mi")
```

```{r}
score(dag2, data = data12, type = "bic")
```

```{r}
dag3 = empty.graph(nodes = c("estrato", "diaViaje", "tipoTransporte", "horaPico"))

arc_set3 = matrix(c("estrato", "diaViaje",
                      "diaViaje", "horaPico",
                      "estrato", "tipoTransporte"),
                    byrow = TRUE, ncol = 2,
                    dimnames = list(NULL, c("from", "to")))
arcs(dag3) = arc_set3
dag3
```

```{r}
arc.strength(dag3, data = data34, criterion = "mi")
```

```{r}
score(dag3, data = data34, type = "bic")
```

```{r}
dag4 = empty.graph(nodes = c("estrato", "tipoTransporte", "diaViaje", "horaPico"))

arc_set4 = matrix(c("estrato", "tipoTransporte",
                    "diaViaje", "horaPico",
                    "diaViaje", "tipoTransporte",
                    "horaPico", "tipoTransporte"),
                  byrow = TRUE, ncol = 2,
                  dimnames = list(NULL, c("from", "to")))
arcs(dag4) = arc_set4
dag4
```

```{r}
arc.strength(dag4, data = data34, criterion = "mi")
```

```{r}
score(dag4, data = data34, type = "bic")
```

```{r}
best_dag_q12 = hc(data12)
fitted_q12 <- bn.fit(best_dag_q12, data = data12)
modelstring(best_dag_q12)
```

```{r}
score(best_dag_q12, data = data12, type = "bic")
```

```{r}
best_dag_q34 = hc(data34)
fitted_q34 <- bn.fit(best_dag_q34, data = data34)
modelstring(best_dag_q34)
```

```{r}
score(best_dag_q34, data = data34, type = "bic")
```

```{mermaid}
flowchart TD
    s(sexo) --> ed(edad)
    s --> tt(tipoTransporte)
    ed --> tt
    ed --> mc(masDeUnCarro)
    tt --> mc
    ed --> e(estrato)
    tt --> e
    mc --> e
```

```{mermaid}
flowchart TD
    e(estrato) --> d(diaViaje)
    e --> tt(tipoTransporte)
    d --> tt
    e --> h(horaPico)
    d --> h
    tt --> h
```

**Query 1**

```{r}
prob_mujer <- cpquery(fitted_q12,
                      event = ((tipoTransporte == "Publico") | (tipoTransporte == "Publico y privado")),
                      evidence = (sexo == "Mujer"), n = 10^6)

prob_hombre <- cpquery(fitted_q12,
                       event = ((tipoTransporte == "Publico") | (tipoTransporte == "Publico y privado")),
                       evidence = (sexo == "Hombre"))

prob_mujer
prob_hombre

```

**Query 2**

```{r}
prob_adulto_bajo <- cpquery(fitted_q12,
                      event = ((masDeUnCarro == "Si") | (tipoTransporte == "Privado") | (tipoTransporte == "Publico y privado")),
                      evidence = ((edad == "Adulto joven") & (estrato == "Bajo")))


prob_adulto_bajo
```

**Query 3**

```{r}
prob_viaje_habil <- cpquery(fitted_q34,
        event = (diaViaje == "Entre semana"),
        evidence = (estrato == "Bajo"))

prob_viaje_no_habil <- cpquery(fitted_q34,
        event = (diaViaje == "Sabado"),
        evidence = (estrato == "Bajo"))

prob_viaje_habil
prob_viaje_no_habil
```

viajan mas en dias habiles

**Query 4**

```{r}

p_pico <- cpquery(fitted_q34, 
                  event = ((tipoTransporte == "Publico") | (tipoTransporte == "Publico y privado")), 
                  evidence = (horaPico == "Si"))


p_no_pico <- cpquery(fitted_q34, 
                     event = ((tipoTransporte == "Publico") | (tipoTransporte == "Publico y privado")), 
                     evidence = (horaPico == "No"))

p_pico
p_no_pico

```
